{% set name = "asyncpg" %}
{% set version = "0.26.0" %}
{% set sha256 = "77e684a24fee17ba3e487ca982d0259ed17bae1af68006f4cf284b23ba20ea2c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - typing_extensions  # [py<38]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - asyncpg

about:
  home: https://github.com/MagicStack/asyncpg
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A fast PostgreSQL Database Client Library for Python/asyncio.
  description: |
    asyncpg is a database interface library designed specifically for
    PostgreSQL and Python/asyncio. asyncpg is an efficient, clean
    implementation of PostgreSQL server binary protocol for use with Python's
    asyncio framework.
  doc_url: https://magicstack.github.io/asyncpg
  dev_url: https://github.com/MagicStack/asyncpg

extra:
  recipe-maintainers:
    - nehaljwani
    - xhochy
