{% set name = "asyncpg" %}
{% set version = "0.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c551e9928ab6707602f44811817f82ba3c446e018bfe1d3abecc8ba5f3eac851
  patches:
    - 1101.patch
    - 11101c6eff3abb8c734b8880f2a6bd5bc3160255.patch

build:
  number: 0
  script:
    - del asyncpg\pgproto\pgproto.c asyncpg\protocol\protocol.c  # [win]
    - rm asyncpg/pgproto/pgproto.c asyncpg/protocol/protocol.c   # [unix]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - setuptools
    - pip
  run:
    - python
    - typing_extensions >=3.7.4.3  # [py<38]
    - async-timeout >=4.0.3

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - asyncpg

about:
  home: https://github.com/MagicStack/asyncpg
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A fast PostgreSQL Database Client Library for Python/asyncio.
  description: |
    asyncpg is a database interface library designed specifically for
    PostgreSQL and Python/asyncio. asyncpg is an efficient, clean
    implementation of PostgreSQL server binary protocol for use with Python's
    asyncio framework.
  doc_url: https://magicstack.github.io/asyncpg
  dev_url: https://github.com/MagicStack/asyncpg

extra:
  recipe-maintainers:
    - nehaljwani
    - xhochy
