{% set name = "asyncpg" %}
{% set version = "0.17.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "adccada0bb13230360e4569b4b3eea8bb21693ffc5042275933abcb538ab3fbb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # Not using pypi URL because the source dist has incorrect C files for windows
  url: https://github.com/MagicStack/{{ name }}/archive/v{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_value }}

build:
  number: 1000
  script: python setup.py install  --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - cython
    - setuptools
    - toolchain
  run:
    - python

test:
  imports:
    - asyncpg

about:
  home: https://github.com/MagicStack/asyncpg
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: A fast PostgreSQL Database Client Library for Python/asyncio.
  description: |
    asyncpg is a database interface library designed specifically for
    PostgreSQL and Python/asyncio. asyncpg is an efficient, clean
    implementation of PostgreSQL server binary protocol for use with Python's
    asyncio framework.
  doc_url: https://magicstack.github.io/asyncpg
  dev_url: https://github.com/MagicStack/asyncpg

extra:
  recipe-maintainers:
    - nehaljwani
    - xhochy
