travis:
  secure:
    BINSTAR_TOKEN: JRUds/LxIMjCu6hk+7arwoTb5TzDfcTWeUzT4ClMPSxVa8LB2rw7UrAUmQnBGpD9oUvGnbJaRtkdvYWCkaePRlNML2VnUdJd1bqfp128EBMlOmM3gVaIWSLp7Ou5N8YNf5Ry142Dq20tEV66L4ty8+/Pi7sadSksqSdilPHBkrvUnbcQtoi9k4k2jnQfjNl2SxPH6s+4bE8clG3ab5GqMsihyvoknDZwUrXGo7b5t0/dAQxDaY+fziIqVpKp3Aws1STpWN/4LpPJgwBfAir80hVPh3rKUN9pGSwss27+X+GoBTIQp+hdUs08c3Jm1u+yFByR6d/N4G3Z8wIYiLNhRsj40y20XQ83QdzMfUE375WWVWeiOgrUhMriPHJJJtJbZSGEff1p5FyTNNYw0Iyoq9y4IH9/F8uHxRSh1LPgpaCy6nYm3UjhyClw74IH8qPHuKeIGv5bSWE4ZWt0XlM8pYGVqddMd9n+9q9BsO8oq+MopCDcYzWrUwrCCTElsKhUX2gB2swxF18BY/L6ZPy4oBhNAj3vLXLSKj7GgucvciYxLhlvOaO1pvDP08o1w828oOnvsmcG4Vm13S7BZZGQiqzUrUAWM/pH/DiBpeLu/ZLBnsaxKmVwrVBYx+WMvbpy+r6U1qwZKhpDp39xk/jov6exWrC60kff76CQ4piOUdA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
